# docker-compose.yml

version: '3.8'
services:
  db:
    image: postgres:13
    container_name: leadgen_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - leadgen-network

  app:
    build: .
    container_name: leadgen_app
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "${APP_PORT}:8080"
    networks:
      - leadgen-network
    command: ["sh", "-c", "until nc -z -v -w30 db 5432; do echo 'Waiting for database...'; sleep 1; done; ./main"]

networks:
  leadgen-network:
    driver: bridge

volumes:
  postgres_data:
